#!/usr/bin/env python3
"""Emit ScholarsGallery/Localizable.xcstrings from BASE (en) + per-locale overrides."""
from __future__ import annotations

import json
from pathlib import Path

# English source strings (keys = stable catalog identifiers)
BASE: dict[str, str] = {
    "tab.exhibitions": "Exhibitions",
    "tab.studio": "Studio",
    "tab.scholarship": "Scholarship",
    "tab.collection": "Collection",
    "app.brandName": "ScholarsGallery",
    "home.loadingExhibitions": "Loading exhibitions…",
    "home.unableToLoadExhibitions": "Unable to load exhibitions",
    "home.noExhibitionsAvailable": "No exhibitions available",
    "common.refresh": "Refresh",
    "detail.segmentExperience": "Experience",
    "detail.segmentWorks": "Works",
    "detail.segmentEssay": "Essay",
    "detail.loadingExperience": "Loading experience…",
    "detail.noRoomExperience": "No room experience available",
    "works.loadingWorks": "Loading works…",
    "works.unableToLoadWorks": "Unable to load works",
    "works.noWorksInExhibition": "No works in this exhibition",
    "artwork.navTitle": "Artwork",
    "artwork.acquireEdition": "Acquire Edition %1$lld/%2$lld",
    "artwork.removeFavorite": "Remove Favorite",
    "artwork.saveToFavorites": "Save to Favorites",
    "essay.byAuthor": "By %@",
    "essay.references": "References",
    "essay.loading": "Loading essay…",
    "essay.noEssayAvailable": "No essay available",
    "scholarship.loading": "Loading scholarship…",
    "scholarship.unableToLoad": "Unable to load scholarship",
    "scholarship.noEssays": "No essays available",
    "scholarship.navTitle": "Scholarship",
    "collection.loading": "Loading collection…",
    "collection.emptyTitle": "No collected editions yet",
    "collection.emptyDescription": "Acquire an edition from an artwork to build your collection.",
    "collection.navTitle": "Collection",
    "collection.acquiredPrefix": "Acquired",
    "collection.certificateLabel": "Certificate: %@",
    "acquisition.navTitle": "Acquisition",
    "acquisition.sectionArtwork": "Artwork",
    "acquisition.sectionAcquisition": "Acquisition",
    "acquisition.sectionDelivery": "Delivery Bundle",
    "acquisition.purchasedOn": "Purchased On",
    "acquisition.certificateId": "Certificate ID",
    "acquisition.editionRights": "Edition Rights",
    "acquisition.editionRightsValue": "Display on personal Apple devices",
    "delivery.iphoneAsset": "iPhone/iPad Display Asset",
    "delivery.hiResExport": "High-resolution Still Export",
    "delivery.scholarshipPackage": "Scholarship Metadata Package",
    "studio.navTitle": "Generation Studio",
    "studio.promptLabel": "Prompt",
    "studio.generateArtwork": "Generate Artwork",
    "studio.result": "Result",
    "studio.providerFormat": "Provider: %@",
    "studio.statusFormat": "Status: %@",
    "studio.recentGenerations": "Recent Generations",
    "studio.defaultPrompt": "Create a luminous, research-driven abstract composition for an immersive digital exhibition.",
    "scholarshipDetail.loadingEssay": "Loading essay…",
    "scholarshipDetail.essayUnavailable": "Essay unavailable",
    "checkout.unavailable": "Checkout unavailable.",
    "checkout.urlReady": "Checkout URL ready: %@",
    "checkout.currentlyUnavailable": "Checkout currently unavailable.",
    "error.invalidGeneratedEndpoint": "Invalid generated artworks endpoint.",
    "error.serverInvalid": "Invalid response from server.",
    "error.decodeFailed": "Data could not be decoded.",
    "error.networkCached": "Network unavailable. Showing cached data when possible.",
    "error.networkConnect": "Unable to connect to server.",
    "error.unexpected": "An unexpected error occurred.",
    "icloud.unavailable": "iCloud account unavailable. Sign into iCloud to enable cloud backup.",
    "studio.uiTestError": "Generation failed in UI test mode.",
}

# Locale code -> partial overrides (missing keys fall back to English)
OVERRIDES: dict[str, dict[str, str]] = {
    "zh-Hans": {
        "tab.exhibitions": "展览",
        "tab.studio": "工作室",
        "tab.scholarship": "学术",
        "tab.collection": "收藏",
        "home.loadingExhibitions": "正在加载展览…",
        "home.unableToLoadExhibitions": "无法加载展览",
        "home.noExhibitionsAvailable": "暂无展览",
        "common.refresh": "刷新",
        "detail.segmentExperience": "体验",
        "detail.segmentWorks": "作品",
        "detail.segmentEssay": "文章",
        "works.loadingWorks": "正在加载作品…",
        "works.unableToLoadWorks": "无法加载作品",
        "works.noWorksInExhibition": "本展览暂无作品",
        "artwork.navTitle": "作品",
        "artwork.acquireEdition": "获取版本 %1$lld/%2$lld",
        "artwork.removeFavorite": "取消收藏",
        "artwork.saveToFavorites": "加入收藏",
        "essay.byAuthor": "作者：%@",
        "essay.references": "参考文献",
        "scholarship.navTitle": "学术",
        "collection.navTitle": "收藏",
        "collection.emptyTitle": "尚无收藏版本",
        "collection.emptyDescription": "从作品页面获取版本以建立收藏。",
        "collection.acquiredPrefix": "获取于",
        "collection.certificateLabel": "证书编号：%@",
        "acquisition.navTitle": "获取记录",
        "studio.navTitle": "生成工作室",
        "studio.promptLabel": "提示词",
        "studio.generateArtwork": "生成作品",
        "studio.recentGenerations": "最近生成",
        "checkout.unavailable": "结账不可用。",
        "checkout.currentlyUnavailable": "结账暂时不可用。",
    },
    "zh-Hant": {
        "tab.exhibitions": "展覽",
        "tab.studio": "工作室",
        "tab.scholarship": "學術",
        "tab.collection": "收藏",
        "home.loadingExhibitions": "正在載入展覽…",
        "home.unableToLoadExhibitions": "無法載入展覽",
        "home.noExhibitionsAvailable": "暫無展覽",
        "common.refresh": "重新整理",
        "detail.segmentExperience": "體驗",
        "detail.segmentWorks": "作品",
        "detail.segmentEssay": "文章",
        "works.loadingWorks": "正在載入作品…",
        "works.unableToLoadWorks": "無法載入作品",
        "works.noWorksInExhibition": "本展覽暫無作品",
        "artwork.navTitle": "作品",
        "artwork.removeFavorite": "取消收藏",
        "artwork.saveToFavorites": "加入收藏",
        "essay.byAuthor": "作者：%@",
        "essay.references": "參考文獻",
        "scholarship.navTitle": "學術",
        "collection.navTitle": "收藏",
        "studio.navTitle": "生成工作室",
        "studio.generateArtwork": "生成作品",
    },
    "ja": {
        "tab.exhibitions": "展覧会",
        "tab.studio": "スタジオ",
        "tab.scholarship": "学術",
        "tab.collection": "コレクション",
        "home.loadingExhibitions": "展覧会を読み込み中…",
        "home.unableToLoadExhibitions": "展覧会を読み込めません",
        "home.noExhibitionsAvailable": "展覧会がありません",
        "common.refresh": "更新",
        "detail.segmentExperience": "体験",
        "detail.segmentWorks": "作品",
        "detail.segmentEssay": "エッセイ",
        "works.loadingWorks": "作品を読み込み中…",
        "artwork.navTitle": "作品",
        "artwork.removeFavorite": "お気に入りを解除",
        "artwork.saveToFavorites": "お気に入りに保存",
        "essay.byAuthor": "著者：%@",
        "essay.references": "参考文献",
        "scholarship.navTitle": "学術",
        "collection.navTitle": "コレクション",
        "studio.navTitle": "ジェネレーションスタジオ",
        "studio.generateArtwork": "作品を生成",
    },
    "ko": {
        "tab.exhibitions": "전시",
        "tab.studio": "스튜디오",
        "tab.scholarship": "학술",
        "tab.collection": "컬렉션",
        "home.loadingExhibitions": "전시 불러오는 중…",
        "common.refresh": "새로고침",
        "detail.segmentExperience": "체험",
        "detail.segmentWorks": "작품",
        "detail.segmentEssay": "에세이",
        "artwork.navTitle": "작품",
        "scholarship.navTitle": "학술",
        "collection.navTitle": "컬렉션",
        "studio.navTitle": "생성 스튜디오",
        "studio.generateArtwork": "작품 생성",
    },
    "es": {
        "tab.exhibitions": "Exposiciones",
        "tab.studio": "Estudio",
        "tab.scholarship": "Investigación",
        "tab.collection": "Colección",
        "home.loadingExhibitions": "Cargando exposiciones…",
        "home.unableToLoadExhibitions": "No se pueden cargar las exposiciones",
        "common.refresh": "Actualizar",
        "detail.segmentExperience": "Experiencia",
        "detail.segmentWorks": "Obras",
        "detail.segmentEssay": "Ensayo",
        "artwork.navTitle": "Obra",
        "artwork.removeFavorite": "Quitar favorito",
        "artwork.saveToFavorites": "Guardar en favoritos",
        "essay.byAuthor": "Por %@",
        "essay.references": "Referencias",
        "scholarship.navTitle": "Investigación",
        "collection.navTitle": "Colección",
        "studio.navTitle": "Estudio de generación",
        "studio.generateArtwork": "Generar obra",
    },
    "fr": {
        "tab.exhibitions": "Expositions",
        "tab.studio": "Studio",
        "tab.scholarship": "Recherche",
        "tab.collection": "Collection",
        "home.loadingExhibitions": "Chargement des expositions…",
        "common.refresh": "Actualiser",
        "detail.segmentExperience": "Expérience",
        "detail.segmentWorks": "Œuvres",
        "detail.segmentEssay": "Essai",
        "artwork.navTitle": "Œuvre",
        "essay.byAuthor": "Par %@",
        "essay.references": "Références",
        "scholarship.navTitle": "Recherche",
        "collection.navTitle": "Collection",
        "studio.navTitle": "Studio de génération",
        "studio.generateArtwork": "Générer une œuvre",
    },
    "de": {
        "tab.exhibitions": "Ausstellungen",
        "tab.studio": "Studio",
        "tab.scholarship": "Forschung",
        "tab.collection": "Sammlung",
        "home.loadingExhibitions": "Ausstellungen werden geladen…",
        "common.refresh": "Aktualisieren",
        "detail.segmentExperience": "Erlebnis",
        "detail.segmentWorks": "Werke",
        "detail.segmentEssay": "Essay",
        "artwork.navTitle": "Kunstwerk",
        "essay.byAuthor": "Von %@",
        "essay.references": "Literatur",
        "scholarship.navTitle": "Forschung",
        "collection.navTitle": "Sammlung",
        "studio.navTitle": "Generierungs-Studio",
        "studio.generateArtwork": "Kunstwerk erzeugen",
    },
    "pt-BR": {
        "tab.exhibitions": "Exposições",
        "tab.studio": "Estúdio",
        "tab.scholarship": "Pesquisa",
        "tab.collection": "Coleção",
        "home.loadingExhibitions": "Carregando exposições…",
        "common.refresh": "Atualizar",
        "detail.segmentWorks": "Obras",
        "artwork.navTitle": "Obra",
        "scholarship.navTitle": "Pesquisa",
        "collection.navTitle": "Coleção",
        "studio.generateArtwork": "Gerar obra",
    },
    "ru": {
        "tab.exhibitions": "Выставки",
        "tab.studio": "Студия",
        "tab.scholarship": "Наука",
        "tab.collection": "Коллекция",
        "home.loadingExhibitions": "Загрузка выставок…",
        "common.refresh": "Обновить",
        "detail.segmentWorks": "Работы",
        "artwork.navTitle": "Работа",
        "scholarship.navTitle": "Наука",
        "collection.navTitle": "Коллекция",
        "studio.generateArtwork": "Создать работу",
    },
    "ar": {
        "tab.exhibitions": "المعارض",
        "tab.studio": "الاستوديو",
        "tab.scholarship": "الأكاديمية",
        "tab.collection": "المجموعة",
        "home.loadingExhibitions": "جاري تحميل المعارض…",
        "common.refresh": "تحديث",
        "detail.segmentWorks": "الأعمال",
        "artwork.navTitle": "عمل فني",
        "scholarship.navTitle": "الأكاديمية",
        "collection.navTitle": "المجموعة",
        "studio.generateArtwork": "إنشاء عمل",
    },
    "hi": {
        "tab.exhibitions": "प्रदर्शनियाँ",
        "tab.studio": "स्टूडियो",
        "tab.scholarship": "शोध",
        "tab.collection": "संग्रह",
        "common.refresh": "रीफ़्रेश करें",
        "scholarship.navTitle": "शोध",
        "collection.navTitle": "संग्रह",
        "studio.generateArtwork": "कलाकृति बनाएँ",
    },
    "id": {
        "tab.exhibitions": "Pameran",
        "tab.studio": "Studio",
        "tab.scholarship": "Beasiswa",
        "tab.collection": "Koleksi",
        "common.refresh": "Segarkan",
        "scholarship.navTitle": "Beasiswa",
        "collection.navTitle": "Koleksi",
        "studio.generateArtwork": "Buat karya",
    },
    "vi": {
        "tab.exhibitions": "Triển lãm",
        "tab.studio": "Studio",
        "tab.scholarship": "Học thuật",
        "tab.collection": "Bộ sưu tập",
        "common.refresh": "Làm mới",
        "scholarship.navTitle": "Học thuật",
        "collection.navTitle": "Bộ sưu tập",
        "studio.generateArtwork": "Tạo tác phẩm",
    },
    "th": {
        "tab.exhibitions": "นิทรรศการ",
        "tab.studio": "สตูดิโอ",
        "tab.scholarship": "วิชาการ",
        "tab.collection": "คอลเลกชัน",
        "common.refresh": "รีเฟรช",
        "studio.generateArtwork": "สร้างผลงาน",
    },
    "it": {
        "tab.exhibitions": "Mostre",
        "tab.studio": "Studio",
        "tab.scholarship": "Studi",
        "tab.collection": "Collezione",
        "common.refresh": "Aggiorna",
        "scholarship.navTitle": "Studi",
        "collection.navTitle": "Collezione",
        "studio.generateArtwork": "Genera opera",
    },
    "nl": {
        "tab.exhibitions": "Tentoonstellingen",
        "tab.studio": "Studio",
        "tab.scholarship": "Wetenschap",
        "tab.collection": "Collectie",
        "common.refresh": "Vernieuwen",
        "studio.generateArtwork": "Kunstwerk genereren",
    },
    "pl": {
        "tab.exhibitions": "Wystawy",
        "tab.studio": "Studio",
        "tab.scholarship": "Badania",
        "tab.collection": "Kolekcja",
        "common.refresh": "Odśwież",
        "studio.generateArtwork": "Generuj dzieło",
    },
    "tr": {
        "tab.exhibitions": "Sergiler",
        "tab.studio": "Stüdyo",
        "tab.scholarship": "Burs",
        "tab.collection": "Koleksiyon",
        "common.refresh": "Yenile",
        "studio.generateArtwork": "Eser oluştur",
    },
    "uk": {
        "tab.exhibitions": "Виставки",
        "tab.studio": "Студія",
        "tab.scholarship": "Наука",
        "tab.collection": "Колекція",
        "common.refresh": "Оновити",
        "studio.generateArtwork": "Створити твір",
    },
    "he": {
        "tab.exhibitions": "תערוכות",
        "tab.studio": "סטודיו",
        "tab.scholarship": "מלגות",
        "tab.collection": "אוסף",
        "common.refresh": "רענן",
        "studio.generateArtwork": "צור יצירה",
    },
    "sv": {
        "tab.exhibitions": "Utställningar",
        "tab.studio": "Studio",
        "tab.scholarship": "Forskning",
        "tab.collection": "Samling",
        "common.refresh": "Uppdatera",
        "studio.generateArtwork": "Generera konstverk",
    },
    "da": {
        "tab.exhibitions": "Udstillinger",
        "tab.studio": "Studio",
        "tab.collection": "Samling",
        "common.refresh": "Opdater",
    },
    "fi": {
        "tab.exhibitions": "Näyttelyt",
        "tab.studio": "Studio",
        "tab.collection": "Kokoelma",
        "common.refresh": "Päivitä",
    },
    "nb": {
        "tab.exhibitions": "Utstillinger",
        "tab.studio": "Studio",
        "tab.collection": "Samling",
        "common.refresh": "Oppdater",
    },
    "ms": {
        "tab.exhibitions": "Pameran",
        "tab.studio": "Studio",
        "tab.collection": "Koleksi",
        "common.refresh": "Muat semula",
    },
    "fil": {
        "tab.exhibitions": "Mga Eksibisyon",
        "tab.studio": "Studio",
        "tab.collection": "Koleksyon",
        "common.refresh": "I-refresh",
    },
    "sw": {
        "tab.exhibitions": "Maonyesho",
        "tab.studio": "Studio",
        "tab.collection": "Mkusanyiko",
        "common.refresh": "Onyesha upya",
    },
    "cs": {
        "tab.exhibitions": "Výstavy",
        "tab.studio": "Studio",
        "tab.collection": "Sbírka",
        "common.refresh": "Obnovit",
    },
    "ro": {
        "tab.exhibitions": "Expoziții",
        "tab.studio": "Studio",
        "tab.collection": "Colecție",
        "common.refresh": "Reîmprospătare",
    },
    "hu": {
        "tab.exhibitions": "Kiállítások",
        "tab.studio": "Stúdió",
        "tab.collection": "Gyűjtemény",
        "common.refresh": "Frissítés",
    },
    "el": {
        "tab.exhibitions": "Εκθέσεις",
        "tab.studio": "Στούντιο",
        "tab.collection": "Συλλογή",
        "common.refresh": "Ανανέωση",
    },
}

LOCALES = sorted(
    set(["en"])
    | set(OVERRIDES.keys())
    | {
        "es-419",
        "pt-PT",
        "en-GB",
        "en-AU",
        "fr-CA",
        "ca",
        "hr",
        "sk",
        "sl",
        "lt",
        "lv",
        "et",
        "bg",
    }
)


def value_for(locale: str, key: str) -> str:
    if locale == "en":
        return BASE[key]
    if locale in OVERRIDES and key in OVERRIDES[locale]:
        return OVERRIDES[locale][key]
    # Sensible fallbacks for regional variants
    if locale == "es-419" and "es" in OVERRIDES and key in OVERRIDES["es"]:
        return OVERRIDES["es"][key]
    if locale == "pt-PT" and "pt-BR" in OVERRIDES and key in OVERRIDES["pt-BR"]:
        return OVERRIDES["pt-BR"][key]
    if locale in ("en-GB", "en-AU"):
        return BASE[key]
    if locale == "fr-CA" and "fr" in OVERRIDES and key in OVERRIDES["fr"]:
        return OVERRIDES["fr"][key]
    return BASE[key]


def build_strings() -> dict:
    out: dict = {}
    for key, en_val in BASE.items():
        locs: dict = {}
        for loc in LOCALES:
            locs[loc] = {
                "stringUnit": {
                    "state": "translated",
                    "value": value_for(loc, key),
                }
            }
        out[key] = {"extractionState": "manual", "localizations": locs}
    return out


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    target = root / "ScholarsGallery" / "Localizable.xcstrings"
    doc = {
        "sourceLanguage": "en",
        "strings": build_strings(),
        "version": "1.0",
    }
    target.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {target} ({len(BASE)} keys × {len(LOCALES)} locales)")


if __name__ == "__main__":
    main()
